version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    target-branch: "dependenciesUpdate"
    labels:
      - "Dependabot"
  
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    target-branch: "dependenciesUpdate"
    labels:
      - "Dependabot"
